### Get all tasks list (Local)
GET http://localhost:3000/tasks

### Get a single task (Local)
GET http://localhost:3000/tasks/652b578bd31a0419aee491a2

### Create contact (Local)
POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

{
   "title": "[BE] Get Request",
   "description": "Create get request to fetch for all tasks",
   "questPoints": 3,
   "assignee": "iRed",
   "reporter": "Jared Bala",
   "priority": "Highest",
   "startDate": "October 9, 2023",
   "dueDate": "October 15, 2023"
}

### Get all tasks list (Local)
GET https://cse341-personalproject.onrender.com/tasks

### Get a single task (Local)
GET https://cse341-personalproject.onrender.com/tasks/652b578bd31a0419aee491a2

### Create contact (Local)
POST https://cse341-personalproject.onrender.com/tasks HTTP/1.1
Content-Type: application/json

{
   "title": "[BE] Get Request",
   "description": "Create get request to fetch for all tasks",
   "questPoints": 3,
   "assignee": "iRed",
   "reporter": "Jared Bala",
   "priority": "Highest",
   "startDate": "2023-10-09T16:00:00.000+00:00",
   "dueDate": "2023-10-14T16:00:00.000+00:00"
}